source 'https://github.com/CocoaPods/Specs.git'
platform :ios, ‘8.0’

target "SocketClient" do

pod 'MBProgressHUD', '0.9'             
pod 'NYXImagesKit', '2.3'
pod 'UIImage+BlurredFrame', '0.0.4'
pod 'AFNetworking', '~> 2.3.1' 
pod 'SDAutoLayout', '~> 2.1.3’
pod 'SVProgressHUD'

end
